### ISSUE TITLE
tmux-prefix-highlight doesn't show at all

### ISSUE THREAD

**Issue by nkcfan** [sei40kr/tmux-onedark#1]
This is my .tmux.conf

```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'sei40kr/tmux-onedark'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by andrebras** [comment]
Hi @nkcfan,

Looking into the last two commits, it seems that the dependency from `tmux-plugins/tmux-prefix-highlight` was removed (here: 1e931ddc84dbe4ed14e197a3c0fbe2bf2396f3bc) and dependencies to `tmux-plugins/tmux-battery` and `ctjhoa/tmux-cpu` were added (here: 277c117d9ccfc46bd2525aef980290f301002ab6)

**Comment by nkcfan** [comment]
Just check the latest version of all the plugins, and it is working. Thanks @andrebras !
